const LOCAL_WALLET = "LOCAL_WALLET";
const IS_WALLET_CONNECTED = "IS_WALLET_CONNECTED";
const CONNECTED_METAMASK = "CONNECTED_METAMASK";

export { LOCAL_WALLET, IS_WALLET_CONNECTED, CONNECTED_METAMASK };
