export const ALL_TRANSACTION_HISTORY = 'ALL_TRANSACTION_HISTORY';
export const INSIGHT_DATA = "INSIGHT_DATA";
export const NETFLOW_GRAPH = "NETFLOW_GRAPH";
export const TRANSACTION_FILTER = "TRANSACTION_FILTER";

export const GAS_FEES = "GAS_FEES";
export const COUNTER_PARTY_VOLUME = "COUNTER_PARTY_VOLUME";
export const PORTFOLIO_ASSET = "PORTFOLIO_ASSET";
export const AVERAGE_COST_BASIS = "AVERAGE_COST_BASIS";
