export const ALL_TRANSACTION_HISTORY = "ALL_TRANSACTION_HISTORY";
export const INSIGHT_DATA = "INSIGHT_DATA";
export const NETFLOW_GRAPH = "NETFLOW_GRAPH";
export const TRANSACTION_FILTER = "TRANSACTION_FILTER";

export const GAS_FEES = "GAS_FEES";
export const COUNTER_PARTY_VOLUME = "COUNTER_PARTY_VOLUME";
export const PORTFOLIO_ASSET = "PORTFOLIO_ASSET";
export const AVERAGE_COST_BASIS = "AVERAGE_COST_BASIS";
export const ALL_TRANSACTION_HISTORY_HOME = "ALL_TRANSACTION_HISTORY_HOME";
export const AVERAGE_COST_RESET = "AVERAGE_COST_RESET";
export const AVERAGE_COST_SORT = "AVERAGE_COST_SORT";

// Inflow outflow chart
export const INFLOW_OUTFLOW_CHART_DATA = "INFLOW_OUTFLOW_CHART_DATA";
export const INFLOW_OUTFLOW_TIME_TAB = "INFLOW_OUTFLOW_TIME_TAB";
export const INFLOW_OUTFLOW_WALLET = "INFLOW_OUTFLOW_WALLET";
export const INFLOW_OUTFLOW_CHART_ASSET_SELECTED =
  "INFLOW_OUTFLOW_CHART_ASSET_SELECTED";
export const INFLOW_OUTFLOW_CHART_ASSET_LIST =
  "INFLOW_OUTFLOW_CHART_ASSET_LIST";
export const DARK_MODE = "DARK_MODE";
