// const COIN_RATE_LIST = "COIN_RATE_LIST";
const TOP_USER_WALLET_LIST = "TOP_USER_WALLET_LIST";
const TOP_DEFAULT_VALUES = "TOP_DEFAULT_VALUES";

// asset value chart graphValue
const TOP_ASSET_VALUE_GRAPH = "TOP_ASSET_VALUE_GRAPH";

// asset value chart graphValue
const TOP_ASSET_VALUE_GRAPH_YEAR = "TOP_ASSET_VALUE_GRAPH_YEAR";

// asset value chart graphValue
const TOP_ASSET_VALUE_GRAPH_MONTH = "TOP_ASSET_VALUE_GRAPH_MONTH";

// asset value chart graphValue
const TOP_ASSET_VALUE_GRAPH_DAY = "TOP_ASSET_VALUE_GRAPH_DAY";

// External events
const TOP_EXTERNAL_EVENTS = "TOP_EXTERNAL_EVENTS";

// get yesterday balance
const TOP_YESTERDAY_BALANCE = "TOP_YESTERDAY_BALANCE";

export {
  TOP_USER_WALLET_LIST,
  TOP_DEFAULT_VALUES,
  TOP_YESTERDAY_BALANCE,
  TOP_ASSET_VALUE_GRAPH,
  TOP_EXTERNAL_EVENTS,
  TOP_ASSET_VALUE_GRAPH_DAY,
  TOP_ASSET_VALUE_GRAPH_MONTH,
  TOP_ASSET_VALUE_GRAPH_YEAR,
};

// Intelligence
export const TOP_ALL_TRANSACTION_HISTORY = "TOP_ALL_TRANSACTION_HISTORY";
export const TOP_INSIGHT_DATA = "TOP_INSIGHT_DATA";
export const TOP_NETFLOW_GRAPH = "TOP_NETFLOW_GRAPH";
export const TOP_TRANSACTION_FILTER = "TOP_TRANSACTION_FILTER";

export const TOP_GAS_FEES = "TOP_GAS_FEES";
export const TOP_COUNTER_PARTY_VOLUME = "TOP_COUNTER_PARTY_VOLUME";
export const TOP_PORTFOLIO_ASSET = "TOP_PORTFOLIO_ASSET";
export const TOP_AVERAGE_COST_BASIS = "TOP_AVERAGE_COST_BASIS";
export const TOP_ALL_TRANSACTION_HISTORY_HOME = "TOP_ALL_TRANSACTION_HISTORY_HOME";
export const TOP_AVERAGE_COST_RESET = "TOP_AVERAGE_COST_RESET";
export const TOP_AVERAGE_COST_SORT = "TOP_AVERAGE_COST_SORT";