export const SET_COMMON_REDUCER = 'SET_COMMON_REDUCER';
export const WALLET_LIST_UPDATED = "WALLET_LIST_UPDATED";
export const SET_DEFAULT_VALUE = "SET_DEFAULT_VALUE";
export const PAGE_POPUP = "PAGE_POPUP";