export const SET_COMMON_REDUCER = "SET_COMMON_REDUCER";
export const WALLET_LIST_UPDATED = "WALLET_LIST_UPDATED";
export const CURRENT_USER_PAYMENT_PLAN = "CURRENT_USER_PAYMENT_PLAN";
export const SET_DEFAULT_VALUE = "SET_DEFAULT_VALUE";
export const PAGE_POPUP = "PAGE_POPUP";
export const TOP_SET_DEFAULT_VALUE = "TOP_SET_DEFAULT_VALUE";
export const LOCAL_ADD_WALLET_LIST = "LOCAL_ADD_WALLET_LIST";
