export const GET_BACK_TEST_CHART_DATA = "GET_BACK_TEST_CHART_DATA";
export const GET_BACK_TEST_TABLE_DATA = "GET_BACK_TEST_TABLE_DATA";
export const GET_BACK_TEST_QUERIES = "GET_BACK_TEST_QUERIES";
export const GET_LATEST_STRATEGY_ID = "GET_LATEST_STRATEGY_ID";
