const COIN_RATE_LIST = 'COIN_RATE_LIST';
const USER_WALLET_LIST = 'USER_WALLET_LIST';
const DEFAULT_VALUES = 'DEFAULT_VALUES';

// asset value chart graphValue
const ASSET_VALUE_GRAPH = "ASSET_VALUE_GRAPH";

// External events
const EXTERNAL_EVENTS = "EXTERNAL_EVENTS";

// get yesterday balance
const YESTERDAY_BALANCE = "YESTERDAY_BALANCE";




export {
  COIN_RATE_LIST,
  USER_WALLET_LIST,
  DEFAULT_VALUES,
  YESTERDAY_BALANCE,
  ASSET_VALUE_GRAPH,
  EXTERNAL_EVENTS,

};